CREATE TABLE IF NOT EXISTS ilanlar (
    id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    "txtIlanBasligi" varchar(250),
    "txtSektor" varchar(150),
    "txtSehirIlce" varchar(150),
    "txtIlanDetay" text,
    "numIlanDurum" smallint NOT NULL DEFAULT 1
);

CREATE INDEX IF NOT EXISTS ix_ilanlar_num_ilan_durum
    ON ilanlar ("numIlanDurum");
