using ErtamIK.WebPortal.Models;
using Npgsql;
using System.Data.Common;

namespace ErtamIK.WebPortal.Services;

public sealed class PortalRepository(
    IConfiguration configuration,
    PasswordService passwordService)
{
    private NpgsqlConnection CreateConnection()
    {
        string value = configuration.GetConnectionString("DefaultConnection")
            ?? throw new InvalidOperationException("DefaultConnection tanımlanmamış.");

        if (value.StartsWith("postgresql://", StringComparison.OrdinalIgnoreCase) ||
            value.StartsWith("postgres://", StringComparison.OrdinalIgnoreCase))
        {
            Uri uri = new(value);
            string[] userInfo = uri.UserInfo.Split(':', 2);
            value = new NpgsqlConnectionStringBuilder
            {
                Host = uri.Host,
                Port = uri.IsDefaultPort ? 5432 : uri.Port,
                Database = uri.AbsolutePath.Trim('/'),
                Username = Uri.UnescapeDataString(userInfo[0]),
                Password = userInfo.Length > 1 ? Uri.UnescapeDataString(userInfo[1]) : "",
                SslMode = SslMode.Require
            }.ConnectionString;
        }

        return new NpgsqlConnection(value);
    }

    public async Task InitializeAsync(CancellationToken cancellationToken = default)
    {
        const string schema = """
            CREATE TABLE IF NOT EXISTS users (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name varchar(120) NOT NULL,
                email varchar(255) NOT NULL,
                password_hash varchar(500) NOT NULL,
                role varchar(30) NOT NULL DEFAULT 'User',
                is_active boolean NOT NULL DEFAULT true,
                created_at timestamptz NOT NULL DEFAULT now()
            );
            CREATE UNIQUE INDEX IF NOT EXISTS ux_users_email_lower ON users (lower(email));

            CREATE TABLE IF NOT EXISTS blog_posts (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                title varchar(220) NOT NULL,
                summary varchar(500) NOT NULL,
                content text NOT NULL,
                category varchar(80) NOT NULL DEFAULT 'Haber',
                is_published boolean NOT NULL DEFAULT true,
                published_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS applications (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                job_id integer NOT NULL,
                user_id integer NOT NULL REFERENCES users(id),
                full_name varchar(120) NOT NULL,
                email varchar(255) NOT NULL,
                phone varchar(30) NOT NULL,
                cover_letter text NOT NULL,
                reference_code varchar(30) NOT NULL UNIQUE,
                status varchar(60) NOT NULL DEFAULT 'Alındı',
                created_at timestamptz NOT NULL DEFAULT now(),
                updated_at timestamptz NOT NULL DEFAULT now()
            );
            CREATE INDEX IF NOT EXISTS ix_applications_user ON applications(user_id);
            CREATE INDEX IF NOT EXISTS ix_applications_reference ON applications(reference_code);

            CREATE TABLE IF NOT EXISTS contact_messages (
                id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                full_name varchar(120) NOT NULL,
                email varchar(255) NOT NULL,
                phone varchar(30),
                subject varchar(160) NOT NULL,
                message text NOT NULL,
                is_read boolean NOT NULL DEFAULT false,
                created_at timestamptz NOT NULL DEFAULT now()
            );

            CREATE TABLE IF NOT EXISTS site_content (
                content_key varchar(80) PRIMARY KEY,
                content_value text NOT NULL,
                updated_at timestamptz NOT NULL DEFAULT now()
            );

            INSERT INTO site_content(content_key, content_value) VALUES
                ('privacy_text', 'Ertam A.Ş. olarak aday ve ziyaretçi verilerini yalnızca işe alım, iletişim ve yasal yükümlülüklerin yerine getirilmesi amaçlarıyla işleriz. Başvuru sırasında paylaşılan bilgiler yetkili insan kaynakları personeli dışında üçüncü kişilerle paylaşılmaz. Veriler gerekli teknik ve idari güvenlik tedbirleri uygulanarak saklanır. Bilgilerinize erişme, düzeltme veya silinmesini talep etme hakkınız vardır. Talepleriniz için iletişim sayfamızdaki kanalları kullanabilirsiniz.'),
                ('contact_address', 'Gebze / Kocaeli'),
                ('contact_phone', '+90 (530) 744 16 07'),
                ('contact_email', 'info@ertam-ik.com.tr')
            ON CONFLICT (content_key) DO NOTHING;

            INSERT INTO blog_posts(title, summary, content, category)
            SELECT 'Doğru İşe Alım Süreci Nasıl Tasarlanır?',
                   'Yetkinlik, deneyim ve kurum kültürünü birlikte değerlendiren işe alım yaklaşımı.',
                   'Başarılı bir işe alım süreci yalnızca özgeçmiş incelemekten ibaret değildir. Rolün ihtiyaçları açıkça belirlenmeli, aday deneyimi korunmalı ve değerlendirme ölçütleri tüm adaylara eşit biçimde uygulanmalıdır. Ertam A.Ş. olarak insan odağını ve sürdürülebilir istihdamı sürecin merkezinde tutuyoruz.',
                   'İnsan Kaynakları'
            WHERE NOT EXISTS (SELECT 1 FROM blog_posts);

            INSERT INTO blog_posts(title, summary, content, category)
            SELECT 'Ertam Kariyer Portalı Yayında',
                   'Açık pozisyonları inceleyebileceğiniz ve başvurularınızı takip edebileceğiniz yeni kariyer portalımız açıldı.',
                   'Yeni kariyer portalımız ile ilanları tek noktadan inceleyebilir, güvenli hesabınızı oluşturarak başvurabilir ve başvuru kodunuzla süreci takip edebilirsiniz.',
                   'Haber'
            WHERE (SELECT count(*) FROM blog_posts) = 1;
            """;

        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync(cancellationToken);
        await using (NpgsqlCommand command = new(schema, connection))
        {
            await command.ExecuteNonQueryAsync(cancellationToken);
        }

        string adminEmail = configuration["AdminSeed:Email"] ?? "admin@ertam.com.tr";
        string? adminPassword = configuration["AdminSeed:Password"];
        if (!string.IsNullOrWhiteSpace(adminPassword))
        {
            const string adminSql = """
                INSERT INTO users(full_name, email, password_hash, role)
                VALUES ('Ertam Yönetici', @email, @hash, 'Admin')
                ON CONFLICT (lower(email)) DO UPDATE
                SET role = 'Admin', is_active = true;
                """;
            await using NpgsqlCommand command = new(adminSql, connection);
            command.Parameters.AddWithValue("email", adminEmail.Trim().ToLowerInvariant());
            command.Parameters.AddWithValue("hash", passwordService.Hash(adminPassword));
            await command.ExecuteNonQueryAsync(cancellationToken);
        }
    }

    public async Task<IReadOnlyList<Ilan>> GetActiveJobsAsync()
    {
        const string sql = """
            SELECT id, "txtIlanBasligi", "txtSektor", "txtSehirIlce", "txtIlanDetay", "numIlanDurum"
            FROM ilanlar WHERE "numIlanDurum" = 1 ORDER BY id DESC
            """;
        List<Ilan> result = [];
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(MapJob(reader));
        }
        return result;
    }

    public async Task<Ilan?> GetJobAsync(int id)
    {
        const string sql = """
            SELECT id, "txtIlanBasligi", "txtSektor", "txtSehirIlce", "txtIlanDetay", "numIlanDurum"
            FROM ilanlar WHERE id = @id
            """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("id", id);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? MapJob(reader) : null;
    }

    public async Task<IReadOnlyList<Ilan>> GetAllJobsAsync()
    {
        const string sql = """
            SELECT id, "txtIlanBasligi", "txtSektor", "txtSehirIlce", "txtIlanDetay", "numIlanDurum"
            FROM ilanlar ORDER BY id DESC
            """;
        List<Ilan> result = [];
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync()) result.Add(MapJob(reader));
        return result;
    }

    public async Task SaveJobAsync(JobEditViewModel model)
    {
        string sql = model.Id == 0
            ? """
              INSERT INTO ilanlar("txtIlanBasligi", "txtSektor", "txtSehirIlce", "txtIlanDetay", "numIlanDurum")
              VALUES (@title, @sector, @location, @detail, @status)
              """
            : """
              UPDATE ilanlar SET "txtIlanBasligi"=@title, "txtSektor"=@sector,
              "txtSehirIlce"=@location, "txtIlanDetay"=@detail, "numIlanDurum"=@status
              WHERE id=@id
              """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("title", model.Title);
        command.Parameters.AddWithValue("sector", model.Sector);
        command.Parameters.AddWithValue("location", model.Location);
        command.Parameters.AddWithValue("detail", model.Detail);
        command.Parameters.AddWithValue("status", (short)(model.IsActive ? 1 : 0));
        if (model.Id != 0) command.Parameters.AddWithValue("id", model.Id);
        await command.ExecuteNonQueryAsync();
    }

    public async Task<UserAccount?> FindUserByEmailAsync(string email)
    {
        const string sql = """
            SELECT id, full_name, email, password_hash, role
            FROM users WHERE lower(email)=lower(@email) AND is_active=true
            """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("email", email.Trim());
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? MapUser(reader) : null;
    }

    public async Task<int> CreateUserAsync(RegisterViewModel model, string passwordHash)
    {
        const string sql = """
            INSERT INTO users(full_name, email, password_hash, role)
            VALUES (@name, @email, @hash, 'User') RETURNING id
            """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("name", model.FullName.Trim());
        command.Parameters.AddWithValue("email", model.Email.Trim().ToLowerInvariant());
        command.Parameters.AddWithValue("hash", passwordHash);
        return Convert.ToInt32(await command.ExecuteScalarAsync());
    }

    public async Task<IReadOnlyList<BlogPost>> GetPublishedPostsAsync(int limit = 20)
    {
        const string sql = """
            SELECT id, title, summary, content, category, published_at
            FROM blog_posts WHERE is_published=true ORDER BY published_at DESC LIMIT @limit
            """;
        List<BlogPost> result = [];
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("limit", limit);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync()) result.Add(MapPost(reader));
        return result;
    }

    public async Task<BlogPost?> GetPostAsync(int id, bool includeDraft = false)
    {
        string sql = """
            SELECT id, title, summary, content, category, published_at
            FROM blog_posts WHERE id=@id
            """ + (includeDraft ? "" : " AND is_published=true");
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("id", id);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        return await reader.ReadAsync() ? MapPost(reader) : null;
    }

    public async Task<IReadOnlyList<BlogPost>> GetAllPostsAsync() =>
        await GetPostsInternalAsync();

    private async Task<IReadOnlyList<BlogPost>> GetPostsInternalAsync()
    {
        const string sql = """
            SELECT id, title, summary, content, category, published_at
            FROM blog_posts ORDER BY published_at DESC
            """;
        List<BlogPost> result = [];
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync()) result.Add(MapPost(reader));
        return result;
    }

    public async Task SavePostAsync(BlogEditViewModel model)
    {
        string sql = model.Id == 0
            ? """
              INSERT INTO blog_posts(title, summary, content, category, is_published)
              VALUES (@title, @summary, @content, @category, @published)
              """
            : """
              UPDATE blog_posts SET title=@title, summary=@summary, content=@content,
              category=@category, is_published=@published, updated_at=now() WHERE id=@id
              """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("title", model.Title);
        command.Parameters.AddWithValue("summary", model.Summary);
        command.Parameters.AddWithValue("content", model.Content);
        command.Parameters.AddWithValue("category", model.Category);
        command.Parameters.AddWithValue("published", model.IsPublished);
        if (model.Id != 0) command.Parameters.AddWithValue("id", model.Id);
        await command.ExecuteNonQueryAsync();
    }

    public async Task<SiteContent> GetSiteContentAsync()
    {
        Dictionary<string, string> values = new(StringComparer.OrdinalIgnoreCase);
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new("SELECT content_key, content_value FROM site_content", connection);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync()) values[reader.GetString(0)] = reader.GetString(1);
        return new SiteContent
        {
            PrivacyText = values.GetValueOrDefault("privacy_text", ""),
            ContactAddress = values.GetValueOrDefault("contact_address", ""),
            ContactPhone = values.GetValueOrDefault("contact_phone", ""),
            ContactEmail = values.GetValueOrDefault("contact_email", "")
        };
    }

    public async Task SaveSiteContentAsync(SiteContent model)
    {
        const string sql = """
            INSERT INTO site_content(content_key, content_value) VALUES
            ('privacy_text', @privacy), ('contact_address', @address),
            ('contact_phone', @phone), ('contact_email', @email)
            ON CONFLICT(content_key) DO UPDATE SET content_value=excluded.content_value, updated_at=now()
            """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("privacy", model.PrivacyText);
        command.Parameters.AddWithValue("address", model.ContactAddress);
        command.Parameters.AddWithValue("phone", model.ContactPhone);
        command.Parameters.AddWithValue("email", model.ContactEmail);
        await command.ExecuteNonQueryAsync();
    }

    public async Task AddContactMessageAsync(ContactViewModel model)
    {
        const string sql = """
            INSERT INTO contact_messages(full_name, email, phone, subject, message)
            VALUES (@name, @email, @phone, @subject, @message)
            """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("name", model.FullName.Trim());
        command.Parameters.AddWithValue("email", model.Email.Trim());
        command.Parameters.AddWithValue("phone", model.Phone?.Trim() ?? "");
        command.Parameters.AddWithValue("subject", model.Subject.Trim());
        command.Parameters.AddWithValue("message", model.Message.Trim());
        await command.ExecuteNonQueryAsync();
    }

    public async Task<IReadOnlyList<ContactMessage>> GetMessagesAsync()
    {
        const string sql = """
            SELECT id, full_name, email, coalesce(phone,''), subject, message, created_at
            FROM contact_messages ORDER BY created_at DESC
            """;
        List<ContactMessage> result = [];
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(new ContactMessage
            {
                Id = reader.GetInt32(0),
                FullName = reader.GetString(1),
                Email = reader.GetString(2),
                Phone = reader.GetString(3),
                Subject = reader.GetString(4),
                Message = reader.GetString(5),
                CreatedAt = reader.GetDateTime(6)
            });
        }
        return result;
    }

    public async Task<string> AddApplicationAsync(int userId, ApplicationViewModel model)
    {
        string reference = $"ER-{DateTime.UtcNow:yyMMdd}-{Guid.NewGuid().ToString("N")[..8].ToUpperInvariant()}";
        const string sql = """
            INSERT INTO applications(job_id, user_id, full_name, email, phone, cover_letter, reference_code)
            VALUES (@job, @user, @name, @email, @phone, @letter, @reference)
            """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        command.Parameters.AddWithValue("job", model.JobId);
        command.Parameters.AddWithValue("user", userId);
        command.Parameters.AddWithValue("name", model.FullName.Trim());
        command.Parameters.AddWithValue("email", model.Email.Trim());
        command.Parameters.AddWithValue("phone", model.Phone.Trim());
        command.Parameters.AddWithValue("letter", model.CoverLetter.Trim());
        command.Parameters.AddWithValue("reference", reference);
        await command.ExecuteNonQueryAsync();
        return reference;
    }

    public async Task<IReadOnlyList<JobApplication>> GetUserApplicationsAsync(int userId)
    {
        const string sql = ApplicationSelect + " WHERE a.user_id=@user ORDER BY a.created_at DESC";
        return await GetApplicationsAsync(sql, ("user", userId));
    }

    public async Task<IReadOnlyList<JobApplication>> GetAllApplicationsAsync()
    {
        const string sql = ApplicationSelect + " ORDER BY a.created_at DESC";
        return await GetApplicationsAsync(sql);
    }

    public async Task<JobApplication?> FindApplicationAsync(string reference, string email)
    {
        const string sql = ApplicationSelect + """
             WHERE upper(a.reference_code)=upper(@reference) AND lower(a.email)=lower(@email)
            """;
        IReadOnlyList<JobApplication> result =
            await GetApplicationsAsync(sql, ("reference", reference.Trim()), ("email", email.Trim()));
        return result.FirstOrDefault();
    }

    public async Task UpdateApplicationStatusAsync(int id, string status)
    {
        string[] allowed = ["Alındı", "İnceleniyor", "Görüşme", "Olumlu", "Olumsuz"];
        if (!allowed.Contains(status)) throw new ArgumentException("Geçersiz başvuru durumu.");
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(
            "UPDATE applications SET status=@status, updated_at=now() WHERE id=@id", connection);
        command.Parameters.AddWithValue("status", status);
        command.Parameters.AddWithValue("id", id);
        await command.ExecuteNonQueryAsync();
    }

    public async Task<AdminDashboardViewModel> GetDashboardAsync()
    {
        const string sql = """
            SELECT
              (SELECT count(*) FROM users WHERE role='User'),
              (SELECT count(*) FROM applications),
              (SELECT count(*) FROM ilanlar WHERE "numIlanDurum"=1),
              (SELECT count(*) FROM contact_messages)
            """;
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        await reader.ReadAsync();
        AdminDashboardViewModel result = new()
        {
            UserCount = Convert.ToInt32(reader.GetInt64(0)),
            ApplicationCount = Convert.ToInt32(reader.GetInt64(1)),
            ActiveJobCount = Convert.ToInt32(reader.GetInt64(2)),
            MessageCount = Convert.ToInt32(reader.GetInt64(3))
        };
        await reader.CloseAsync();
        result.RecentApplications = (await GetAllApplicationsAsync()).Take(8).ToList();
        return result;
    }

    private const string ApplicationSelect = """
        SELECT a.id, a.job_id, a.user_id, coalesce(i."txtIlanBasligi",'Silinmiş İlan'),
               a.full_name, a.email, a.phone, a.cover_letter, a.reference_code, a.status, a.created_at
        FROM applications a LEFT JOIN ilanlar i ON i.id=a.job_id
        """;

    private async Task<IReadOnlyList<JobApplication>> GetApplicationsAsync(
        string sql,
        params (string Name, object Value)[] parameters)
    {
        List<JobApplication> result = [];
        await using NpgsqlConnection connection = CreateConnection();
        await connection.OpenAsync();
        await using NpgsqlCommand command = new(sql, connection);
        foreach ((string name, object value) in parameters) command.Parameters.AddWithValue(name, value);
        await using NpgsqlDataReader reader = await command.ExecuteReaderAsync();
        while (await reader.ReadAsync())
        {
            result.Add(new JobApplication
            {
                Id = reader.GetInt32(0),
                JobId = reader.GetInt32(1),
                UserId = reader.GetInt32(2),
                JobTitle = reader.GetString(3),
                FullName = reader.GetString(4),
                Email = reader.GetString(5),
                Phone = reader.GetString(6),
                CoverLetter = reader.GetString(7),
                ReferenceCode = reader.GetString(8),
                Status = reader.GetString(9),
                CreatedAt = reader.GetDateTime(10)
            });
        }
        return result;
    }

    private static Ilan MapJob(DbDataReader reader) => new()
    {
        Id = reader.GetInt32(0),
        txtIlanBasligi = reader.IsDBNull(1) ? "" : reader.GetString(1),
        txtSektor = reader.IsDBNull(2) ? "" : reader.GetString(2),
        txtSehirIlce = reader.IsDBNull(3) ? "" : reader.GetString(3),
        txtIlanDetay = reader.IsDBNull(4) ? "" : reader.GetString(4),
        numIlanDurum = Convert.ToByte(reader.GetInt16(5))
    };

    private static UserAccount MapUser(DbDataReader reader) => new()
    {
        Id = reader.GetInt32(0),
        FullName = reader.GetString(1),
        Email = reader.GetString(2),
        PasswordHash = reader.GetString(3),
        Role = reader.GetString(4)
    };

    private static BlogPost MapPost(DbDataReader reader) => new()
    {
        Id = reader.GetInt32(0),
        Title = reader.GetString(1),
        Summary = reader.GetString(2),
        Content = reader.GetString(3),
        Category = reader.GetString(4),
        PublishedAt = reader.GetDateTime(5)
    };
}
